package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	resourceschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"terraform-provider-noozle/internal/client"
)

var (
	_ resource.Resource                = &ntfyOutletResource{}
	_ resource.ResourceWithConfigure   = &ntfyOutletResource{}
	_ resource.ResourceWithImportState = &ntfyOutletResource{}
)

type ntfyOutletClient interface {
	CreateNtfyOutlet(context.Context, client.NtfyOutletCreateRequest) (client.NtfyOutlet, error)
	GetNtfyOutlet(context.Context, int64) (client.NtfyOutlet, error)
	UpdateNtfyOutlet(context.Context, int64, client.NtfyOutletUpdateRequest) error
	DeleteNtfyOutlet(context.Context, int64) error
	SetNtfyTopic(context.Context, int64, string) error
	ClearNtfyNotifyPolicy(context.Context, int64) error
	ClearNtfyServerURL(context.Context, int64) error
	DeleteNtfyOutletOperation(context.Context, int64) (client.OutletOperation, error)
	GetTypedOutletStatus(context.Context, string, int64, int64) (client.OutletStatus, error)
}

type ntfyOutletResource struct {
	outletLifecycle[ntfyOutletResourceModel]
}

type ntfyOutletAdapter struct{ client ntfyOutletClient }

type ntfyOutletResourceModel struct {
	ID                types.Int64  `tfsdk:"id"`
	Name              types.String `tfsdk:"name"`
	Description       types.String `tfsdk:"description"`
	Enabled           types.Bool   `tfsdk:"enabled"`
	Topic             types.String `tfsdk:"topic"`
	EffectiveTopic    types.String `tfsdk:"effective_topic"`
	NotifyPolicy      types.String `tfsdk:"notify_policy"`
	ServerURL         types.String `tfsdk:"server_url"`
	ApplyStatus       types.String `tfsdk:"apply_status"`
	LastApplyError    types.String `tfsdk:"last_apply_error"`
	ConfigGeneration  types.Int64  `tfsdk:"config_generation"`
	AppliedGeneration types.Int64  `tfsdk:"applied_generation"`
}

func NewNtfyOutletResource() resource.Resource {
	return &ntfyOutletResource{outletLifecycle: newOutletLifecycle("ntfy Outlet", newNtfyOutletAdapter)}
}

func (r *ntfyOutletResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ntfy_outlet"
}

func (r *ntfyOutletResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = resourceschema.Schema{
		MarkdownDescription: "Manages a Noozle ntfy outlet.",
		Attributes: map[string]resourceschema.Attribute{
			"id": resourceschema.Int64Attribute{
				MarkdownDescription: "Unique identifier of the outlet.",
				Computed:            true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"name": resourceschema.StringAttribute{
				MarkdownDescription: "Name presented for the outlet.",
				Required:            true,
			},
			"description": resourceschema.StringAttribute{
				MarkdownDescription: "Optional note explaining the outlet purpose.",
				Optional:            true,
			},
			"enabled": resourceschema.BoolAttribute{
				MarkdownDescription: "Whether the outlet is active.",
				Required:            true,
			},
			"topic": resourceschema.StringAttribute{
				MarkdownDescription: "ntfy topic suffix. Noozle adds a creator-specific prefix to form the effective topic.",
				Required:            true,
			},
			"effective_topic": resourceschema.StringAttribute{
				MarkdownDescription: "Full creator-specific ntfy topic generated by Noozle.",
				Computed:            true,
			},
			"notify_policy": resourceschema.StringAttribute{
				MarkdownDescription: "Notification policy for routed matches. Use FIRST_ONLY to suppress duplicates or ALL to emit every match.",
				Optional:            true,
			},
			"server_url": resourceschema.StringAttribute{
				MarkdownDescription: "Optional ntfy base URL. Omit for the default ntfy deployment.",
				Optional:            true,
			},
			"apply_status": resourceschema.StringAttribute{
				MarkdownDescription: "Observed apply/runtime status for the outlet.",
				Computed:            true,
			},
			"last_apply_error": resourceschema.StringAttribute{
				MarkdownDescription: "Last observed apply/runtime error message.",
				Computed:            true,
			},
			"config_generation": resourceschema.Int64Attribute{
				MarkdownDescription: "Desired outlet config generation.",
				Computed:            true,
			},
			"applied_generation": resourceschema.Int64Attribute{
				MarkdownDescription: "Last observed applied config generation.",
				Computed:            true,
			},
		},
	}
}

func newNtfyOutletAdapter(providerData any) (outletLifecycleAdapter[ntfyOutletResourceModel], diag.Diagnostics) {
	outletClient, ok := providerData.(ntfyOutletClient)
	if !ok {
		return nil, diag.Diagnostics{diag.NewErrorDiagnostic(
			"Unexpected Provider Data Type",
			fmt.Sprintf("Expected ntfy outlet client, got: %T. Please report this provider bug.", providerData),
		)}
	}
	return ntfyOutletAdapter{client: outletClient}, nil
}

func (a ntfyOutletAdapter) Create(ctx context.Context, _ tfsdk.Config, plan ntfyOutletResourceModel) (outletLifecycleResult[ntfyOutletResourceModel], diag.Diagnostics) {
	ctx, recorder := client.WithOutletOperationRecorder(ctx)
	outlet, err := a.client.CreateNtfyOutlet(ctx, client.NtfyOutletCreateRequest{
		Name:         plan.Name.ValueString(),
		Description:  stringValueOrEmpty(plan.Description),
		Enabled:      plan.Enabled.ValueBool(),
		Topic:        plan.Topic.ValueString(),
		NotifyPolicy: stringPointerValue(plan.NotifyPolicy),
		ServerURL:    stringPointerValue(plan.ServerURL),
	})
	if err != nil {
		return outletLifecycleResult[ntfyOutletResourceModel]{}, diag.Diagnostics{diag.NewErrorDiagnostic("Unable to Create ntfy Outlet", err.Error())}
	}
	if err := observeFinalTypedOutletOperation(ctx, a.client, recorder, "ntfy", outlet.ID, plan.Enabled.ValueBool()); err != nil {
		return outletLifecycleResult[ntfyOutletResourceModel]{}, diag.Diagnostics{diag.NewErrorDiagnostic("Unable to Observe ntfy Outlet Lifecycle", err.Error())}
	}
	return outletLifecycleResult[ntfyOutletResourceModel]{State: ntfyOutletModelFromAPI(outlet, plan.Topic)}, nil
}

func (a ntfyOutletAdapter) Read(ctx context.Context, state ntfyOutletResourceModel) (outletLifecycleResult[ntfyOutletResourceModel], diag.Diagnostics) {
	outlet, err := a.client.GetNtfyOutlet(ctx, state.ID.ValueInt64())
	if err != nil {
		if client.IsNotFound(err) {
			return outletLifecycleResult[ntfyOutletResourceModel]{Removed: true}, nil
		}
		return outletLifecycleResult[ntfyOutletResourceModel]{}, diag.Diagnostics{diag.NewErrorDiagnostic("Unable to Read ntfy Outlet", err.Error())}
	}
	return outletLifecycleResult[ntfyOutletResourceModel]{State: ntfyOutletModelFromAPI(outlet, state.Topic)}, nil
}

func (a ntfyOutletAdapter) Update(ctx context.Context, _ tfsdk.Config, plan, state ntfyOutletResourceModel) (outletLifecycleResult[ntfyOutletResourceModel], diag.Diagnostics) {
	ctx, recorder := client.WithOutletOperationRecorder(ctx)
	if err := a.client.UpdateNtfyOutlet(ctx, state.ID.ValueInt64(), client.NtfyOutletUpdateRequest{
		Name:         plan.Name.ValueString(),
		Description:  stringValueOrEmpty(plan.Description),
		Enabled:      plan.Enabled.ValueBool(),
		Topic:        plan.Topic.ValueString(),
		NotifyPolicy: stringPointerValue(plan.NotifyPolicy),
		ServerURL:    stringPointerValue(plan.ServerURL),
	}); err != nil {
		return outletLifecycleResult[ntfyOutletResourceModel]{}, diag.Diagnostics{diag.NewErrorDiagnostic("Unable to Update ntfy Outlet", err.Error())}
	}
	if plan.NotifyPolicy.IsNull() && !state.NotifyPolicy.IsNull() {
		if err := a.client.ClearNtfyNotifyPolicy(ctx, state.ID.ValueInt64()); err != nil {
			return outletLifecycleResult[ntfyOutletResourceModel]{}, diag.Diagnostics{diag.NewErrorDiagnostic("Unable to Clear ntfy Notify Policy", err.Error())}
		}
	}
	if plan.ServerURL.IsNull() && !state.ServerURL.IsNull() {
		if err := a.client.ClearNtfyServerURL(ctx, state.ID.ValueInt64()); err != nil {
			return outletLifecycleResult[ntfyOutletResourceModel]{}, diag.Diagnostics{diag.NewErrorDiagnostic("Unable to Clear ntfy Server URL", err.Error())}
		}
	}

	outlet, err := a.client.GetNtfyOutlet(ctx, state.ID.ValueInt64())
	if err != nil {
		return outletLifecycleResult[ntfyOutletResourceModel]{}, diag.Diagnostics{diag.NewErrorDiagnostic("Unable to Refresh ntfy Outlet", err.Error())}
	}
	if err := observeFinalTypedOutletOperation(ctx, a.client, recorder, "ntfy", outlet.ID, plan.Enabled.ValueBool()); err != nil {
		return outletLifecycleResult[ntfyOutletResourceModel]{}, diag.Diagnostics{diag.NewErrorDiagnostic("Unable to Observe ntfy Outlet Lifecycle", err.Error())}
	}
	return outletLifecycleResult[ntfyOutletResourceModel]{State: ntfyOutletModelFromAPI(outlet, plan.Topic)}, nil
}

func (a ntfyOutletAdapter) Delete(ctx context.Context, state ntfyOutletResourceModel) diag.Diagnostics {
	operation, err := a.client.DeleteNtfyOutletOperation(ctx, state.ID.ValueInt64())
	if err != nil && !client.IsNotFound(err) {
		return diag.Diagnostics{diag.NewErrorDiagnostic("Unable to Delete ntfy Outlet", err.Error())}
	}
	if err == nil && operation.DesiredGeneration != 0 {
		if err := observeTypedOutletLifecycle(ctx, a.client, "ntfy", state.ID.ValueInt64(), operation.DesiredGeneration, false, true); err != nil {
			return diag.Diagnostics{diag.NewErrorDiagnostic("Unable to Observe ntfy Outlet Lifecycle", err.Error())}
		}
	}
	return nil
}

func ntfyOutletModelFromAPI(outlet client.NtfyOutlet, configuredTopic types.String) ntfyOutletResourceModel {
	if configuredTopic.IsNull() || configuredTopic.IsUnknown() {
		configuredTopic = types.StringValue(outlet.Topic)
	}

	return ntfyOutletResourceModel{
		ID:                types.Int64Value(outlet.ID),
		Name:              types.StringValue(outlet.Name),
		Description:       nullableString(outlet.Description),
		Enabled:           types.BoolValue(outlet.Enabled),
		Topic:             configuredTopic,
		EffectiveTopic:    types.StringValue(outlet.Topic),
		NotifyPolicy:      nullableStringPointer(outlet.NotifyPolicy),
		ServerURL:         nullableStringPointer(outlet.ServerURL),
		ApplyStatus:       nullableString(outlet.ApplyStatus),
		LastApplyError:    nullableString(outlet.LastApplyError),
		ConfigGeneration:  types.Int64Value(outlet.ConfigGeneration),
		AppliedGeneration: types.Int64Value(outlet.AppliedGeneration),
	}
}
